### ISSUE TITLE
Unable to run an example

### ISSUE THREAD

**Issue by bhupinders** [ilovepdf/ilovepdf-nodejs#10]
Hi, I am trying to run a simple csv extract from a pdf but getting some errors, not able to figure out the issue. 

This is my script:
```
const ILovePDFApi = require('@ilovepdf/ilovepdf-nodejs');
const fs = require('fs');

const ilovepdf = new ILovePDFApi('PUBLIC_KEY', 'SECRET_KEY');;

const task = ilovepdf.newTask('rotate');

task.start()
.then(() => {
    return task.addFile('temp.pdf');
})
.then(() => {
    return task.process();
})
.then(() => {
    return task.download();
})
.then((data) => {
    fs.writeFileSync('data.txt', data);
}).catch(error=>{
    console.log(error);
});
```

And I get the following error:

```
Error: Request failed with status code 400
    at createError (/Users/kk/Documents/work/personal/data_api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/kk/Documents/work/personal/data_api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/kk/Documents/work/personal/data_api/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: 'https://api53.ilovepdf.com/v1/upload',
    method: 'post',
    data: '{"task":"g27d4mrsg3ztmnzAgm5d3njAghzyrq10t0ntj4ylw4fsn7w9Ax06rrfjr16xzkzryf75lmrgkAs97hythl6sAn5s0drgghcllzlfqm7jx71w8sq6ymsd05tfhrysnjt4lltg9f8f4hgwk260qcc3cxxyvy","cloud_file":"temp.pdf"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=UTF-8',
      Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJwcm9qZWN0X3B1YmxpY181N2ZkZThhNTVlNWQ2NWZjOTcyMWEyNzZkYWE0YTdmYV96Mm0tNjI2YWQ3MzkxNTBhMTc2YzRjNGU5MDE5ZWE2MzQ3ZWE4IiwiaXNzIjoiYXBpLmlsb3ZlcGRmLmNvbSIsImlhdCI6MTY3ODc4MzM4OC4xODN9.D2htopo_VJwfy-b3A0WX7YQkRILAj-I18yUxU_kllOA',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 189
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [Function: transformResponse],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'text',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api53.ilovepdf.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api53.ilovepdf.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 22,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /v1/upload HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json;charset=UTF-8\r\n' +
      'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJwcm9qZWN0X3B1YmxpY181N2ZkZThhNTVlNWQ2NWZjOTcyMWEyNzZkYWE0YTdmYV96Mm0tNjI2YWQ3MzkxNTBhMTc2YzRjNGU5MDE5ZWE2MzQ3ZWE4IiwiaXNzIjoiYXBpLmlsb3ZlcGRmLmNvbSIsImlhdCI6MTY3ODc4MzM4OC4xODN9.D2htopo_VJwfy-b3A0WX7YQkRILAj-I18yUxU_kllOA\r\n' +
      'User-Agent: axios/0.21.4\r\n' +
      'Content-Length: 189\r\n' +
      'Host: api53.ilovepdf.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1/upload',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api53.ilovepdf.com/v1/upload',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api53.ilovepdf.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 189,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api53.ilovepdf.com/v1/upload',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      server: 'nginx/1.20.2',
      date: 'Tue, 14 Mar 2023 08:43:18 GMT',
      'content-type': 'application/json; charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      expires: 'Mon, 26 Jul 1997 05:00:00 GMT',
      'last-modified': 'Tue, 14 Mar 2023 08:43:18 GMT',
      'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      pragma: 'no-cache',
      'access-control-allow-credentials': 'false',
      'access-control-expose-headers': 'X-Pagination-Current-Page',
      vary: 'Accept',
      'x-rate-limit-limit': '5000',
      'x-rate-limit-remaining': '4999',
      'x-rate-limit-reset': '0',
      'set-cookie': [Array]
    },
    config: {
      url: 'https://api53.ilovepdf.com/v1/upload',
      method: 'post',
      data: '{"task":"g27d4mrsg3ztmnzAgm5d3njAghzyrq10t0ntj4ylw4fsn7w9Ax06rrfjr16xzkzryf75lmrgkAs97hythl6sAn5s0drgghcllzlfqm7jx71w8sq6ymsd05tfhrysnjt4lltg9f8f4hgwk260qcc3cxxyvy","cloud_file":"temp.pdf"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Function: transformResponse],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'text',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      validateStatus: [Function: validateStatus],
      transitional: [Object]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /v1/upload HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=UTF-8\r\n' +
        'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJwcm9qZWN0X3B1YmxpY181N2ZkZThhNTVlNWQ2NWZjOTcyMWEyNzZkYWE0YTdmYV96Mm0tNjI2YWQ3MzkxNTBhMTc2YzRjNGU5MDE5ZWE2MzQ3ZWE4IiwiaXNzIjoiYXBpLmlsb3ZlcGRmLmNvbSIsImlhdCI6MTY3ODc4MzM4OC4xODN9.D2htopo_VJwfy-b3A0WX7YQkRILAj-I18yUxU_kllOA\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 189\r\n' +
        'Host: api53.ilovepdf.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/upload',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api53.ilovepdf.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by diego-ilovepdf** [comment]
Hi @bhupinders ! The problem is that you are not using the `rotate` param to specify the rotation.

Here you can find an example https://github.com/ilovepdf/ilovepdf-nodejs/blob/master/src/samples/rotate.ts

**Comment by bhupinders** [comment]
@diego-ilovepdf Thanks for the quick reply!. Sorry I was trying different methods and forgot to change while pasting it here. I switched it back to 'extract' but still getting similar error!

```
const task = ilovepdf.newTask('extract');

task.start()
.then(() => {
    return task.addFile('temp.pdf');
})
.then(() => {
    return task.process({ detailed: true });
})
.then(() => {
    return task.download();
})
.then((data) => {
    fs.writeFileSync('data.txt', data);
}).catch(error=>{
    console.log(error);
});
```

And the error log
```
Error: Request failed with status code 400
    at createError (/Users/kk/Documents/work/personal/data_api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/kk/Documents/work/personal/data_api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/kk/Documents/work/personal/data_api/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: 'https://api28.ilovepdf.com/v1/upload',
    method: 'post',
    data: '{"task":"g27d4mrsg3ztmnzAgm5d3njAg235pftfmhv2AspAvj0z6cbcbq7p6jlh06772tyc0zhw23m3jz8r32xq0k6j1mjd9Acm1bf3f940z82b02xzgg10j3yj6r5qhp9s66t9AfzbA5s5kt8xbzcv83wk09wrdq","cloud_file":"temp.pdf"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=UTF-8',
      Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJwcm9qZWN0X3B1YmxpY181N2ZkZThhNTVlNWQ2NWZjOTcyMWEyNzZkYWE0YTdmYV96Mm0tNjI2YWQ3MzkxNTBhMTc2YzRjNGU5MDE5ZWE2MzQ3ZWE4IiwiaXNzIjoiYXBpLmlsb3ZlcGRmLmNvbSIsImlhdCI6MTY3ODc5MDM4Ny4yNDl9.RyR4JQFiHJGUbNr-LwbmNT3JUp7m3rH2p_lt3WByLSw',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 189
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [Function: transformResponse],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'text',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api28.ilovepdf.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api28.ilovepdf.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 22,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /v1/upload HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json;charset=UTF-8\r\n' +
      'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJwcm9qZWN0X3B1YmxpY181N2ZkZThhNTVlNWQ2NWZjOTcyMWEyNzZkYWE0YTdmYV96Mm0tNjI2YWQ3MzkxNTBhMTc2YzRjNGU5MDE5ZWE2MzQ3ZWE4IiwiaXNzIjoiYXBpLmlsb3ZlcGRmLmNvbSIsImlhdCI6MTY3ODc5MDM4Ny4yNDl9.RyR4JQFiHJGUbNr-LwbmNT3JUp7m3rH2p_lt3WByLSw\r\n' +
      'User-Agent: axios/0.21.4\r\n' +
      'Content-Length: 189\r\n' +
      'Host: api28.ilovepdf.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1/upload',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api28.ilovepdf.com/v1/upload',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api28.ilovepdf.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 189,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api28.ilovepdf.com/v1/upload',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      server: 'nginx/1.18.0',
      date: 'Tue, 14 Mar 2023 10:39:55 GMT',
      'content-type': 'application/json; charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'x-powered-by': 'PHP/7.3.22',
      expires: 'Mon, 26 Jul 1997 05:00:00 GMT',
      'last-modified': 'Tue, 14 Mar 2023 10:39:55 GMT',
      'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      pragma: 'no-cache',
      'access-control-allow-credentials': 'false',
      'access-control-expose-headers': 'X-Pagination-Current-Page',
      vary: 'Accept',
      'x-rate-limit-limit': '5000',
      'x-rate-limit-remaining': '4999',
      'x-rate-limit-reset': '0',
      'set-cookie': [Array]
    },
    config: {
      url: 'https://api28.ilovepdf.com/v1/upload',
      method: 'post',
      data: '{"task":"g27d4mrsg3ztmnzAgm5d3njAg235pftfmhv2AspAvj0z6cbcbq7p6jlh06772tyc0zhw23m3jz8r32xq0k6j1mjd9Acm1bf3f940z82b02xzgg10j3yj6r5qhp9s66t9AfzbA5s5kt8xbzcv83wk09wrdq","cloud_file":"temp.pdf"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Function: transformResponse],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'text',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      validateStatus: [Function: validateStatus],
      transitional: [Object]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /v1/upload HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=UTF-8\r\n' +
        'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJwcm9qZWN0X3B1YmxpY181N2ZkZThhNTVlNWQ2NWZjOTcyMWEyNzZkYWE0YTdmYV96Mm0tNjI2YWQ3MzkxNTBhMTc2YzRjNGU5MDE5ZWE2MzQ3ZWE4IiwiaXNzIjoiYXBpLmlsb3ZlcGRmLmNvbSIsImlhdCI6MTY3ODc5MDM4Ny4yNDl9.RyR4JQFiHJGUbNr-LwbmNT3JUp7m3rH2p_lt3WByLSw\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 189\r\n' +
        'Host: api28.ilovepdf.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/upload',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api28.ilovepdf.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
```

**Comment by diego-ilovepdf** [comment]
Hi @bhupinders  ! You must use ILovePDFFile for local files.

You have an example here in lines 15-16 https://github.com/ilovepdf/ilovepdf-nodejs/blob/master/src/samples/validatepdfa.ts

**Comment by diego-ilovepdf** [comment]
Hi @bhupinders ! Yes, PDF to Excel is a feature only available in the website 😃
