### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by mp3por** [ilovepdf/ilovepdf-nodejs#6]
Hello,

I am unable to run the example with ILOVEPDFFILE. 

My error is 

`internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '....../scripts/VN-4136/node_modules/@ilovepdf/ilovepdf-nodejs/ILovePDFFile' imported from ......./scripts/VN-4136/VN-4136.js
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}`

Steps to reproduce

1. open new dir 
2. npm init -y
3. npm install -s @ilovepdf/ilovepdf-nodejs
4. copy paste example
5. add PK and SK
6. change FILE_PATH to valid PDF file path

**Comment by diego-ilovepdf** [comment]
Hi @mp3por,

It was our fault due to README.md was explaining the old version and also we had a code error.

Please, update the package to the latest version ( now 0.2.1 ) and try to follow the new instructions from the README.md file :).

Cheers,
Diego.
